language: ruby
script: bundle exec rake # run the default task
rvm:
  - "2.1"
  - "2.2"
  - "2.3"
  - "ruby-head"
before_install:
  - gem install bundler -v 1.11.2
  - bundle install
os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
    - rvm: ruby-head
    - rvm: "2.3"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/4a437f53ea927eb122d7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
addons:
    code_climate:
    repo_token: 8f430bd8f1a9e45e545f8abb44dbbae31fe4791689a832aacd5add51f9431e86
